---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-app-1
  labels:
    app: subscriber-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-app-1
  template:
    metadata:
      labels:
        app: subscriber-app-1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber-app-1"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: subscriber-app
        image: vfarcic/dapr-subscriber-app:0.1.5
        ports:
        - containerPort: 8080
        env:
        - name: PUBSUB_NAME
          value: pubsub
        - name: ROUTE
          value: /publish
        - name: TOPICS
          value: A,B

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-app-2
  labels:
    app: subscriber-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-app-2
  template:
    metadata:
      labels:
        app: subscriber-app-2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber-app-2"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: subscriber-app
        image: vfarcic/dapr-subscriber-app:0.1.5
        ports:
        - containerPort: 8080
        env:
        - name: PUBSUB_NAME
          value: pubsub
        - name: ROUTE
          value: /publish
        - name: TOPICS
          value: A,C

---

kind: Service
apiVersion: v1
metadata:
  name: react-form
  labels:
    app: react-form
spec:
  selector:
    app: react-form
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-form
  labels:
    app: react-form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-form
  template:
    metadata:
      labels:
        app: react-form
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "react-form"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: react-form
        image: dapriosamples/pubsub-react-form:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
